# Generated by Django 6.0.2 on 2026-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(unique=True)),
                ("university", models.CharField(max_length=200)),
                ("source_type", models.CharField(max_length=100)),
                ("deadline", models.CharField(blank=True, max_length=200, null=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
